spring:
  profiles:
    active: dev
---
spring:
  profiles: dev

config:
  version: dev_version

---
spring:
  profiles: test

config:
  version: test_version

---
spring:
  profiles: prod

config:
  version: prod_version


